#!python3
"""Problem B. New Lottery Game
https://code.google.com/codejam/contest/2994486/dashboard#s=p1
The Lottery is changing! The Lottery used to have a machine to generate a random winning number. But due to cheating problems, the Lottery has decided to add another machine. The new winning number will be the result of the bitwise-AND operation between the two random numbers generated by the two machines."""

def solve(A, B, K):
    """ y is the number of possible pairs that the machines can generate to make Catalina a winner."""
    winners = 0
    for a in range(A):
        for b in range(B):
            if a & b < K:
                winners += 1
    return winners

if __name__ == "__main__":
    import fileinput
    f = fileinput.input()
    # The first line of the input gives the number of test cases, T. T lines follow, each line with three numbers A B K.

    T = int(f.readline())

    for case in range(1, T+1):
        A, B, K = [int(x) for x in f.readline().split()]
        answer = solve(A, B, K)
        print("Case #{0}: {1}".format(case, answer))
